- name: Import jenkins key from url
  shell: "wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -"

- name: Download Long Term Jenkins release
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present

- name: apt update
  apt:
    name: '*'
    state: latest

- name: Install java
  apt:
    name:
      - default-jre
      - default-jdk
    state: present

- name: Install jenkins
  apt:
    name: jenkins
    state: latest

- name: daemon-reload to pick up config changes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Start jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: started

- name: Install Docker Requirements
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Install Docker
  shell: ' curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
apt-get update -y && \
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin && \
usermod -aG docker jenkins'