- name: Install Docker Requirements
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Install Docker
  shell: ' curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
echo \
"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null && \
apt-get update -y && \
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin && \
usermod -aG docker ubuntu'

- name: "Start docker service"
  service:
    name: "docker"
    state: started
    enabled: yes

- name: "Add key for kubernetes"
  shell: "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add"

- name: "Add repository for kubernetes"
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: disabling selinux
  ufw:
    state: disabled
  ignore_errors: yes
  changed_when: false

- name: "Installing kubeadm, kubectl and kubelet"
  package:
    name: "{{ packages }}"
    state: present
    update_cache: yes

- name: "Enabling kubelet"
  service:
    name: kubelet
    state: started
    enabled: yes
  changed_when: false

- name: "Pulling Images of Docker"
  command: "kubeadm config images pull"

- name: "Changing the Driver"
  copy:
    src: "{{ role_path }}/files/docker_daemon.json"
    dest: "/etc/docker/daemon.json"
  register: driver_output

- name: "Restarting docker service"
  service:
    name: "docker"
    state: restarted

- debug:
    var: driver_output

- name: "Installing iproute-tc "
  package:
    name: "iproute2"
    state: present

- name: "Setting bridge-nf-call-iptables to 1"
  shell: |
       echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
  changed_when: false

- name: "Connect the k8s_Slave to Master"
  shell: "{{ token_1  }}"
  ignore_errors: yes
  register: connected

- debug:
     var: connected